### ISSUE TITLE
Translations for mod

### ISSUE THREAD

**Issue by hearth1an** [hearth1an/hearthian.TheVision#19]
- [ ] Spanish
- [x] Russian (I can do it myself)
- [ ] idk what else needed

**Comment by hearth1an** [comment]
Tlya can make russian translation

**Comment by hearth1an** [comment]
Russian translation made.

**Comment by hearth1an** [comment]
- [x] French translation, [the person who wants  to make it](https://www.reddit.com/r/outerwilds/comments/wuog8r/comment/ill0ozn/?context=3)
- [ ] Italian translation, [the person who wants  to make it](https://studio.youtube.com/channel/UCRq8uV6fJiI6xJP6Np121xQ/comments/inbox?filter=%5B%7B%22name%22%3A%22CONTENT%22%2C%22value%22%3A%7B%22name%22%3A%22FOR%22%2C%22value%22%3A%22italian%22%7D%7D%5D)

**Comment by hearth1an** [comment]
- [ ] German translation, [the person who wants to make it](https://www.reddit.com/user/_Gulli_/)

**Comment by ImSpaceLover** [comment]
Don't know where to send it, so I'll leave it here: 
Russian version (and probably other ones, but I haven't checked) have an untranslated and probably wrongly located string.
![image](https://user-images.githubusercontent.com/64267797/188715282-54f0de1e-adb8-443f-9a5f-6538d9269863.png)
![image](https://user-images.githubusercontent.com/64267797/188715542-f06547f1-842b-4368-969d-4ec521e64fae.png)
Location: ATP Solanum record

**Comment by Alejandro-SB** [comment]
I can do spanish translation, but I want to finish the story first.

**Comment by hearth1an** [comment]
> Don't know where to send it, so I'll leave it here: Russian version (and probably other ones, but I haven't checked) have an untranslated and probably wrongly located string. ![image](https://user-images.githubusercontent.com/64267797/188715282-54f0de1e-adb8-443f-9a5f-6538d9269863.png) ![image](https://user-images.githubusercontent.com/64267797/188715542-f06547f1-842b-4368-969d-4ec521e64fae.png) Location: ATP Solanum record

Fixed few patches ago. This string was added by accident and was removed in last patches

**Comment by hearth1an** [comment]
> I can do spanish translation, but I want to finish the story first.

Someone is already working on it already, but thank you!
