### ISSUE TITLE
Play Test Results

### ISSUE THREAD

**Issue by OneDeuxTriSeiGo** [hearth1an/hearthian.TheVision#21]
First Batch of Reports:

- [x] Type: Ship Log Grammar, Location: Quantum Moon, Context: What if: Change text from `What if I'll show her` to `What if I show her`.

- [x] Type: Sequence Break, Location: Quantum Moon: If you bring the vision staff, solanum will not do her normal game animation sequence at all and there is no option to talk to her. This does not occur on a new profile however I have not tried it after triggering "What If" but without a vision staff.

- [x] Type: Lore, Location: Quantum Moon, Context: Vision Sequence: The vision shows during slides 80-99 that the signal blocker is what alerted the nomai of the eye. From what I can tell, the owlk installed the signal blocker but it was the prisoner disabling that signal blocker for a brief moment that alerted the nomai.

- [x] Type: Graphical Glitch, Location: Quantum Moon: With larger resolutions(multiple monitors spanned horizontally) OW tends to act a bit weird. In my case during the post-vision sequence where the sky changes, the game kinda glitched out and my viewport was put under the terrain.

- [x] Type: Gravity Glitch, Location: Quantum Moon, Context: After returning from quantum moon: While walking the gravity is fine but if you jump, you are treated as if you are in orbit rather than on the moon and you get pulled towards the wall and eventually off the moon.

- [x] Type: Potential Sequence Bug, Location: Quantum Moon, Context: Returning immediately to the eye QM after returning to TH quantum moon: Solanum is still present despite her message on the THQM stating that she is leaving.

- [x] Type: Potential Sequence Bug, Location: Quantum Moon, Context: Leaving the eye quantum moon a second time: The ship is not teleported back to the THQM like in the first instance.

-----

As I progress through the mod, I will document additional issues/suggestions below

------

- [x] Type: Dialogue Grammar, Location: Observatory/Museum, Context: Hornfels' Ernesto Dialogue: Change text from `Where's anglerfish` to `Where's the anglerfish`.

------

- [x] Type: Unexpected Behavior, Location: Brittle Hollow, Context: Visiting all of Solanum's locations: I pulled out my signalscope while on Brittle Hollow with the Quantum Consciousness channel and got a "Ship Log Updated" but there doesn't appear to be any new information.

- [x] Type: Sequence Timing, Location: Brittle Hollow School, Context: Gravity crystal sequence after reading the recording: The sequence activates immediately upon reading the last page. This likely doesn't cause issues when "Pause time while reading" is enabled however when disabled, this causes things to occur while trying to read the prompts. This same thing occurred with the other post-recording sequences however this one was probably the most noticeable as it triggered as soon as I viewed the last page. Recommendation: Add/increase delay on post-recording sequences.

--------

- [x] Type: Sequence Break, Location: ATP Core, Context: Solanum opening ATP: The controls for the ATP are not moved to their updated locations (despite being open, the ATP controls are still set to closed). 

- [x] ~~Type: Quality of Life, Location: The Vessel, Context: Gloaming Coordiantes: The image of the coordinates doesn't seem to map cleanly over the control panels which leaves some ambiguity between which points they map to. I can try redrawing them and seeing if that makes them easier to read (it may not but IDK).~~ Looking at it again, I'm just dumb. It maps over fine but I wasn't paying attention.

**Comment by hearth1an** [comment]
1) Will fix thx!
2) Yes, picking up the torch disables her dialogue things. I made it to avoid animations glitch if she is playing some animation and the vision is starting. Also NomaiVR projection button is the same as start dialogue so it may be glitchy.
3) I decided to not focus on one person such as Prisoner so there's no him in vision.
4) Fixed in last update (like 10 min ago) , well I hope so
5) This bug is known and I don't know how to fix it. It's happening on spawning ship at the TH state of QM. Entering the ship will reset it to normal. Not a big deal imo
6) Yes, there are multiple Solanum states. None of them will disappear. It's explained in new quantum rule (or exception)
7) Will fix thx!

**Comment by OneDeuxTriSeiGo** [comment]
Perfect. I'll keep updating it as I go on. I've decided to wait on the grammar/dialog reports as it's probably more efficient to just do all of those after I play through by reading through the files instead.

**Comment by hearth1an** [comment]
Thanks! That's ok, I'll mark every task completed

**Comment by hearth1an** [comment]
> * [x]  Type: Unexpected Behavior, Location: Brittle Hollow, Context: Visiting all of Solanum's locations: I pulled out my signalscope while on Brittle Hollow with the Quantum Consciousness channel and got a "Ship Log Updated" but there doesn't appear to be any new information.

Solanum is not saying anything about her plans to visit Brittle Hollow. This one added to make player curious about signals. It should add a rumor from Quantum Conciseness shiplog entry that there's such signal to explore :)

> * [x]  Type: Sequence Timing, Location: Brittle Hollow School, Context: Gravity crystal sequence after reading the recording: The sequence activates immediately upon reading the last page. This likely doesn't cause issues when "Pause time while reading" is enabled however when disabled, this causes things to occur while trying to read the prompts. This same thing occurred with the other post-recording sequences however this one was probably the most noticeable as it triggered as soon as I viewed the last page. Recommendation: Add/increase delay on post-recording sequences.

There's actually 2 seconds delay on it. I don't feel like it's an issuem this could happen naturally so you can get back to reading recorder when it will be broken :)

**Comment by OneDeuxTriSeiGo** [comment]
I got up to the TBC point. I'll go through the dialog files now and make my notes from what I saw during playing.

**Comment by hearth1an** [comment]
> * [x]  Type: Sequence Break, Location: ATP Core, Context: Solanum opening ATP: The controls for the ATP are not moved to their updated locations (despite being open, the ATP controls are still set to closed).

That's ok. It just means that Solanum opening it the other way like only Nomai can. (Tbh it would be difficult to make that orb things, they're pure nightmare)

**Comment by hearth1an** [comment]
> * Type: Gravity Glitch, Location: Quantum Moon, Context: After returning from quantum moon: While walking the gravity is fine but if you jump, you are treated as if you are in orbit rather than on the moon and you get pulled towards the wall and eventually off the moon.

fixed in last update

**Comment by hearth1an** [comment]
Thanks for your feedback!
