### ISSUE TITLE
Smth with vision torch entries

### ISSUE THREAD

**Issue by hearth1an** [hearth1an/hearthian.TheVision#24]
![image](https://user-images.githubusercontent.com/106444732/188285078-65313032-2f69-4825-b4a7-2b95c5b03424.png)

"I get this if I use "Find in Map Mode" on "Vision Torch in Damaged Laboratory" entry (new save game). And it shows me another entry in map mode, idk if The Vision or NH bug"

**Comment by dgarroDC** [comment]
This was fixed in #26 ::)
