### ISSUE TITLE
Exception thrown when invoking star system loaded event with parameter [SolarSystem]

### ISSUE THREAD

**Issue by DomiStyle** [hearth1an/hearthian.TheVision#29]
When starting the game through the mod manager I can see "The Vision" in the main menu but upon starting there is nothing in my ship log.

Looking into the log files I can see the following:

```
9/4/2022 10:29:16 PM: [OWML]: Debug: Got subscribed event: AfterAwake of PlayerBody
9/4/2022 10:29:16 PM: [Vanilla Fix]: Debug: Got subscribed event: AfterAwake of PlayerBody
9/4/2022 10:29:16 PM: [New Horizons]: Debug: Got subscribed event: AfterAwake of PlayerBody
9/4/2022 10:29:16 PM: [The Vision]: Debug: Got subscribed event: AfterAwake of PlayerBody
9/4/2022 10:29:16 PM: [NomaiVR]: Debug: Got subscribed event: AfterAwake of PlayerBody
9/4/2022 10:29:16 PM: [New Horizons]: Debug: Loading config from Z:/mnt/data/games/steam/steamapps/common/Outer Wilds/OWML/Mods\xen.NewHorizons\save.json
9/4/2022 10:29:17 PM: [The Vision]: Message: LOADED SYSTEM SolarSystem
9/4/2022 10:29:17 PM: [New Horizons]: Error: Error : Exception thrown when invoking star system loaded event with parameter [SolarSystem]:
System.NullReferenceException: Object reference not set to an instance of an object
  at TheVision.TheVision.SpawnStartProps () [0x00017] in <92ba5a778ea44f1b8b2d64cd0e3a4c3d>:0 
  at TheVision.TheVision.OnStarSystemLoaded (System.String systemName) [0x0002d] in <92ba5a778ea44f1b8b2d64cd0e3a4c3d>:0 
  at UnityEngine.Events.InvokableCall`1[T1].Invoke (T1 args0) [0x00010] in <469e86e97fa2467ebffe49bbd6086325>:0 
  at UnityEngine.Events.UnityEvent`1[T0].Invoke (T0 arg0) [0x00025] in <469e86e97fa2467ebffe49bbd6086325>:0 
  at NewHorizons.Main.OnSceneLoaded (UnityEngine.SceneManagement.Scene scene, UnityEngine.SceneManagement.LoadSceneMode mode) [0x00726] in <c6d1799113c946db97496d5c56b32e90>:0 

```

Full disclaimer, I'm playing on Linux so the issue might be caused by this.

This is most likely an issue with New Horizons so I'm going to open an issue there tomorrow. The other mods that use New Horizons failed to add anything to the ship log as well but without any exception.
Mods like NomaiVR, Quantum Space Buddies or Outer Wilds Online work perfectly fine.

**Comment by hearth1an** [comment]
1. This could happen if  you had Quantum Space Buddies enabled before. Try verify game files and reinstall The Vision after that.
2. Are you using Steam or Epic Store?
3. What mods you have enabled?

**Comment by DomiStyle** [comment]
> This could happen if you had Quantum Space Buddies enabled before. Try verify game files and reinstall The Vision after that.

Yes, I did have Quantum Space Buddies enabled before but I already tried verifying the files but still the same issue. I will try cleaning my game directory completely, maybe there is still something left over somewhere.

> Are you using Steam or Epic Store?

Steam

> What mods you have enabled?

Outer Wilds Mod Manager, OWML, New Horizons, Vanilla Fix and The Vision. I tried with NomaiVR first but am trying without it for now.

**Comment by hearth1an** [comment]
It's working with NomaiVR actually. So here everything should work fine. Jut verify game files, reinstall the vision, and probably new horizons with vanilla fix. This should work, otherwise it could be a linux issue. Let me know if this works!

**Comment by DomiStyle** [comment]
I completely redownloaded Outer Wilds from Steam and just enabled OWML, New Horizons, Vanilla Fix and The Vision.

Unfortunately still the same exception.

**Comment by hearth1an** [comment]
[TheVision.zip](https://github.com/hearth1an/hearthian.TheVision/files/9488734/TheVision.zip)

Try to replace The Vision.dll with this one. Lmk if this works

**Comment by DomiStyle** [comment]
Same exception.

**Comment by hearth1an** [comment]
Ok seems like New Horizons, the mod needed, is not working with linux currently. Sorry about that! You can try a run it on virtual desktop, probably.

**Comment by DomiStyle** [comment]
Thanks anyway!

Will keep this issue open until the issue in New Horizons is fixed. Looking forward to playing The Vision.

**Comment by DomiStyle** [comment]
Should be fixed with https://github.com/Outer-Wilds-New-Horizons/new-horizons/pull/364

Looking forward to playing it this weekend.
