### ISSUE TITLE
Mod is disabled by default.

### ISSUE THREAD

**Issue by dgarroDC** [hearth1an/hearthian.TheVision#41]
The [current release](https://github.com/hearth1an/hearthian.TheVision/releases/tag/v1.0.6) has a config.json file with `"enabled": false`. As a result of this, when I install the mod with the mod manager,  it's disabled by default (even though the mod manager should prevent this, see https://github.com/ow-mods/ow-mod-manager/issues/176).  The config.json file should be deleted from the release.

**Comment by hearth1an** [comment]
Just tested it out. Can confirm: after downloading the mod it's not enabled by default, user have to do it himself manually.

**Comment by hearth1an** [comment]
fixed in v1.0.7
