### ISSUE TITLE
Text redone

### ISSUE THREAD

**Issue by hearth1an** [hearth1an/hearthian.TheVision#42]
I decided to remake all texts to make it more fit Solanum character. Russian is done, now I need someone to help me with polishing English translation. @AlexChaloner can you help me with it? Here's the [link to google sheets](https://docs.google.com/spreadsheets/d/1EkxwJmuGw1kAi2_RL1n6eUr5PdKq7yARf9pjzjWbUss/edit#gid=0) (spoilers). Would be nice if you could take a look at everything in **English (adaptation)**

**Comment by AlexChaloner** [comment]
Will do!

**Comment by AlexChaloner** [comment]
Overall, I really like the changes being made! Did the usual passover with a couple comments/suggestions.

**Comment by hearth1an** [comment]
> Overall, I really like the changes being made! Did the usual passover with a couple comments/suggestions.

Thanks a lot! I liked your suggestions/thoughts as well. (and already replied to all comments).  Do you have any suggestions on this? 
![image](https://user-images.githubusercontent.com/106444732/190019197-6f24e487-5d9d-4d4e-985d-b057c66a5c5d.png)

**Comment by hearth1an** [comment]
1. Two conscious observers continued their journey (in Gloaming Galaxy)
2. You and Solanum have escaped supernova (and met modern nomai in Blackrock)

or smth like that

**Comment by AlexChaloner** [comment]
I like the second suggestion, as it is very similar in style to the escaping supernova ending: 
![image](https://user-images.githubusercontent.com/13849862/190229677-63d306d4-8e85-492c-8ab5-1a5e7c535731.png)

Perhaps:
> You and Solanum escape far beyond the reach of the supernova and meet the Nomai on Blackrock. Together you watch the stars go out.

**Comment by hearth1an** [comment]
I like it! Let's get it then!
