### ISSUE TITLE
The Vision v1.1.0 translations (WIP) 

### ISSUE THREAD

**Issue by hearth1an** [hearth1an/hearthian.TheVision#43]
Hey guys!

I decided to rework all Solanum texts and few shiplogs. All this changes should make player feel character difference less from original Solanum and make decisions more logic based. 

 I made russian and english translation files, tested them and everything was good so far. To make it comfortable for you, I changed translation files for all existing translations so you don't need to translate everything again, just needed fill all "null". 
 
 Can you help me with that? All translation files are in translation folder already.
 @ShoosGun @Deadofnothing @REME-easy @96-38

**Comment by loco-choco** [comment]
aight 👍

**Comment by GlitchedReme** [comment]
sure👍

**Comment by Deadofnothing** [comment]
sure, i'll try to work on that 👍
