### ISSUE TITLE
Return to outerwildsmods

### ISSUE THREAD

**Issue by pakoito** [hearth1an/hearthian.TheVision#53]
Hi! I found this mod through outerwildsmods but it seems to not be there anymore!

**Comment by hearth1an** [comment]
Wow thanks! Seems like last minor update v1.1.1 had some error with uploading the build. I'll try to fix that!

**Comment by hearth1an** [comment]
@pakoito it will be avaliable on website soon again, but it's already downloadable on mod manager
![image](https://user-images.githubusercontent.com/106444732/197754961-1fdf5c1d-112c-4c11-9ed1-38acccdf9686.png)
